openapi: 3.0.1
info:
  version: v1
  title: Shared Objects
paths:
  /dummy:
    get:
      responses: 
        200:
          description: dummy
          
components: 
  schemas: 
    moreAppLocation:
      type: object
